### ISSUE TITLE
Scheluded jobs missfire

### ISSUE THREAD

**Issue by piotrszpruta** [atifaziz/NCrontab#104]
Scheluded jobs run 2 hours later than expected. For example:
It should run every working day at 6:00 (6:00AM) cron expression: 0 6 * * 1-5 - but it runs at 8AM

Tried already with seconds also, but no luck. Any help?

**Comment by piotrszpruta** [comment]
@atifaziz I don't see any stuff related to time zone in NCrontab documentation, or you think of different method?

**Comment by atifaziz** [comment]
That's right, not in NCrontab; it's agnostic. My suggestion was to look elsewhere, perhaps in the (job scheduling) code using NCrontab, and I was thinking of time zones because the two hours difference you mentioned sounds typical of a time zone offset/translation issue.

**Comment by atifaziz** [comment]
I'm going to close this an issue external to NCrontab. Feel free to re-open if you can demonstrate with code that it's a bug in NCrontab.
