### ISSUE TITLE
Validating the expression

### ISSUE THREAD

**Issue by vcaraulean** [atifaziz/NCrontab#11]
I need code to check if expression is valid. I'm doing this now:
```
bool IsCronExpressionValid(string expression)
{
	bool isValid = true;
	CrontabSchedule.TryParse(expression, _ => false, _ => isValid = false);
	return isValid;
}
```
Is there a better way to do it? 

PS: any particular reason it's not exposed in API? Or nobody requested it?

**Comment by atifaziz** [comment]
The better way would be to use the [simpler overload of `CrontabSchedule.TryParse` that just accepts the expression as an argument](https://github.com/atifaziz/NCrontab/blob/c37c9d1aba8166277e59987947c6f5302cc38a66/NCrontab/CrontabSchedule.cs#L99), like this:

bool IsCronExpressionValid(string expression) =>
    CrontabSchedule.TryParse(expression) != null;

**Comment by vcaraulean** [comment]
Indeed, this looks simpler. It's probably a matter of personal taste, but between terseness and explicitness in public apis I'd go for the option that is more "user friendly".

Thanks!

**Comment by atifaziz** [comment]
> but between terseness and explicitness in public apis I'd go for the option that is more "user friendly".

Not sure I understand your comment. What's terse, what's not explicit and what's not user-friendly?

**Comment by vcaraulean** [comment]
I wanted to say that I would prefer a more explicit API over the cleverness and terseness of public API combined with absence of code documentation.

// rant mode on

How that worked for me?
 - I need to check if expression is valid.
 - try ... catch looks dumb, there might be a method for that
 - Oh, cool. There is TryParse method
 - Crap, it's not returning a bool but something else
 - Oh, there's a method that let's me provide an exception factory, let's try that
 - Yep, it works, but far from pretty...

After that, in the evening, I glanced over the code and got a grasp about how it works. But when you're about to add a new feature you want to just "dot into it" with intellisense and get it done.

**Comment by atifaziz** [comment]
@vcaraulean Thanks for taking the time to drop that feedback. I think the right solution here would be to update the README with a quick start section on common use cases for the impatient.

> But when you're about to add a new feature you want to just "dot into it" with intellisense and get it done.

So hopefully NCrontab helped you out and it feels like you got a free :beer: but expecting that everything would be sorted out and perfectly in line with your expectations is somewhat unrealistic/unfair. Nonetheless, I hear you and I'll see if I can find some time to add a quick start section to the README in a future not too distant. Meanwhile, if you want to offer to help there as a “thanks for the :beer:” then I'll take that in the form of a PR. :wink: Perhaps good to open that as a separate issue and follow up there?
