### ISSUE TITLE
Hour semantics

### ISSUE THREAD

**Issue by dsoprea** [atifaziz/NCrontab#14]
I wanted to get clarification on usage edge-cases.

1. Should there be any problems using a range ending on midnight (e.g. 21-0)?
2. Is it possible to provide a range that crosses over midnight (e.g. 21-5)?
3. Is it possible to provide multiple ranges provided as a list (e.g. 21-0, 0-5)?

Thanks.

**Comment by atifaziz** [comment]
> 1. Should there be any problems using a range ending on midnight (e.g. 21-0)?

That's the same as 0-21, so scheduled hours will go from midnight to 9 PM.

> 2. Is it possible to provide a range that crosses over midnight (e.g. 21-5)?

No, that's the same as 5-21.

> 3. Is it possible to provide multiple ranges provided as a list (e.g. 21-0, 0-5)?

Yes but I don't think the result is what you're hoping. It's effectively the same as 0-21.

I think `0 0-5,21-23 * * *` should give what you want.

**Comment by dsoprea** [comment]
Hmm. Might be worth *preventing* (0) from every being used on the right side of a range since the results will probably never be preferable/expected. Either way, we should probably mention this in the README, though there are some mechanics that I won't be able to explain. Could *you* update the README to explain this, as well as, if you have a moment, some sort of explanation as to why?

Thanks.
