### ISSUE TITLE
CrontabSchedule.GetLastOccurrence 

### ISSUE THREAD

**Issue by FelisPhasma** [atifaziz/NCrontab#15]
Hello,
I am trying to use NCronTab in a project I'm working on. I would like to be able to get the previous scheduled occurrence. I have done a little work with trying to implement this, however I have had no success.

**Comment by FelisPhasma** [comment]
From what I've looked at so far, I believe that I need to implement a `CrontabField.Last` method, and then write a `CrontabSchedule.GetLastOccurrence` which calls `CrontabField.Last` instead of ``CrontabField.Next`. I haven't been successful with this...

**Comment by atifaziz** [comment]
You could use [`Pairwise`][pairwise] and [`Prepend`][prepend] from [MoreLINQ][morelinq] to achieve that. Open a Command Prompt and then run `nuget install ncrontab -Version 3.1` followed by `nuget install morelinq -Version 1.4`. Then fire up [C# Interactive][csi] and try the following:

```
Microsoft (R) Visual C# Interactive Compiler version 1.3.1.60616
Copyright (C) Microsoft Corporation. All rights reserved.

Type "#help" for more information.
> #r "ncrontab.3.1.0\lib\net45\NCrontab.dll"
> #r "morelinq.1.4.0\lib\net35\MoreLinq.dll"
> using NCrontab;
> using MoreLinq;
> var schedule = CrontabSchedule.Parse("0 * * * *");
> var occurrences =
.     schedule
.         .GetNextOccurrences(DateTime.Now, DateTime.MaxValue)
.         .Cast<DateTime?>()
.         .Prepend(default(DateTime?))
.         .Pairwise((prev, curr) => new { Previous = prev, Current = curr });
> occurrences.Take(10).ForEach(Console.WriteLine);
{ Previous = , Current = 10/14/2016 5:00:00 PM }
{ Previous = 10/14/2016 5:00:00 PM, Current = 10/14/2016 6:00:00 PM }
{ Previous = 10/14/2016 6:00:00 PM, Current = 10/14/2016 7:00:00 PM }
{ Previous = 10/14/2016 7:00:00 PM, Current = 10/14/2016 8:00:00 PM }
{ Previous = 10/14/2016 8:00:00 PM, Current = 10/14/2016 9:00:00 PM }
{ Previous = 10/14/2016 9:00:00 PM, Current = 10/14/2016 10:00:00 PM }
{ Previous = 10/14/2016 10:00:00 PM, Current = 10/14/2016 11:00:00 PM }
{ Previous = 10/14/2016 11:00:00 PM, Current = 10/15/2016 12:00:00 AM }
{ Previous = 10/15/2016 12:00:00 AM, Current = 10/15/2016 1:00:00 AM }
{ Previous = 10/15/2016 1:00:00 AM, Current = 10/15/2016 2:00:00 AM }
```

Hope this helps.

[morelinq]: https://www.nuget.org/packages/morelinq/1.4.0
[pairwise]: https://morelinq.github.io/1.x/ref/api/html/M_MoreLinq_MoreEnumerable_Pairwise__2.htm
[prepend]: https://morelinq.github.io/1.x/ref/api/html/M_MoreLinq_MoreEnumerable_Prepend__1.htm
[csi]: https://github.com/dotnet/roslyn/wiki/C%23-Interactive-Walkthrough

**Comment by FelisPhasma** [comment]
@atifaziz Yes, this seems to work, however wouldn't it be more optimal to write in support as I described above? Thanks for the help.

**Comment by atifaziz** [comment]
@FelisPhasma Your requirement to recall the previous schedule seems application-specific so I'm reluctant to add it to the library. It can also be solved in several ways. I only showed one quick solution that uses MoreLINQ to show you can achieve what you're after using other existing libraries to build over the occurrences sequence returned by NCrontab. Another simple way would be to hold the previous occurrence of a schedule in some local application state that you recall when moving to the next one.
