### ISSUE TITLE
Cron with every 1 hour works incorrectly

### ISSUE THREAD

**Issue by Lissi4kin** [atifaziz/NCrontab#16]
#Hi,

I have two crons:
1. 40 14/1 * * *
2. 40 14/2 * * *

NCrontab get me result for first:

> 10/19/2016 14:40
> 10/20/2016 14:40
> 10/21/2016 14:40

For second:
> 10/19/2016 14:40
> 10/19/2016 16:40
> 10/19/2016 18:40
> 10/19/2016 20:40
> 10/19/2016 22:40
> 10/20/2016 14:40

First is invalid, it should be 

> 10/19/2016 14:40
> 10/19/2016 15:40
> 10/19/2016 16:40
> etc...

I think it's bug

**Comment by atifaziz** [comment]
> I think it's bug

So it seems. Thanks for reporting this.

A workaround meanwhile would be to write `40 14/1 * * *` instead as `40 14-23 * * *`.

**Comment by Lissi4kin** [comment]
Yes, I did, thanks

**Comment by atifaziz** [comment]
This is now fixed in [release 3.2](https://github.com/atifaziz/NCrontab/releases/tag/v3.2).
