### ISSUE TITLE
.NET Core support

### ISSUE THREAD

**Issue by radenkozec** [atifaziz/NCrontab#18]
Does this library support .NET Core? 
If not do you plan to support it?

**Comment by fabiocav** [comment]
Bump. 

Do you plan on updating to target Netstandard any time in the near future?

**Comment by atifaziz** [comment]
> Does this library support .NET Core?
> If not do you plan to support it?

@radenkozec Yes and actually it is supported and [works](https://github.com/atifaziz/NCrontab/issues/12#issuecomment-225998017). See #12 for more.

> Do you plan on updating to target Netstandard any time in the near future?

@fabiocav I do have a migration in the works in the [`netcore`](https://github.com/atifaziz/NCrontab/tree/netcore) branch but looks like my quantum keeps running out. What's your idea of the near future? Does the [solution](https://github.com/atifaziz/NCrontab/issues/12#issuecomment-225998017) from #12 help meanwhile?

**Comment by atifaziz** [comment]
I've re-opened #12 and closing this as a duplicate. Subscribe to #12 if you're interested in updates.

**Comment by fabiocav** [comment]
@atifaziz sorry for the late reply. Netstandard support would be ideal, but I can take a look at the details on #12 and will comment there if I ran into issues.
I may not get around to testing that for a while, just working on early planning and being proactive here as we intend to migrate Azure Functions (https://github.com/azure/azure-webjobs-sdk-script) to .NET Core and we're using NCrontab there (thank you! :))

**Comment by atifaziz** [comment]
This has now been addressed via #19 and d13d9e415203a892691029b5a12f414c60f10d34.

**Comment by atifaziz** [comment]
NCrontab is now available as a [.NET Standard](https://docs.microsoft.com/en-us/dotnet/articles/standard/library) 1.0 library with [release 3.3](https://github.com/atifaziz/NCrontab/releases/tag/v3.3).
