### ISSUE TITLE
References errors in VS projects

### ISSUE THREAD

**Issue by atifaziz** [atifaziz/NCrontab#22]
When the solution is loaded in VS, projects claim references are in errors as shown in the image below:

![image](https://cloud.githubusercontent.com/assets/20511/21383510/628f9c74-c766-11e6-838f-3581f970abde.png)

There are no errors to be found in the **Error List** and the project just build fine.

This issue might be to do with the `.xproj` tooling just being in preview status.

**Comment by Styxxy** [comment]
Hi,
When upgrading to Visual Studio this should be resolved.
Also see my pull request #32 .
