### ISSUE TITLE
problem in months with 31 days

### ISSUE THREAD

**Issue by unosbaghaie** [atifaziz/NCrontab#23]
when I choose start date 1/29/2017  and the end date as 2/5/2017   with this pattern "* * 2/* 0 0" the result would be 
1/29/2017 12:00:00 AM
1/31/2017 12:00:00 AM
2/1/2017 12:00:00 AM
2/3/2017 12:00:00 AM
2/5/2017 12:00:00 AM
that the issue is with 31st  and 1st . 
could you give me a hint or any suggestion to come up with a solution ?
thanks

**Comment by atifaziz** [comment]
First of all, `"* * 2/* 0 0"` is not a valid crontab expression. If you try the following:

```c#
CrontabSchedule
    .Parse("* * 2/* 0 0")
    .GetNextOccurrences(new DateTime(2017, 1, 29), new DateTime(2017, 2, 5))
```

you will get an exception saying:

> `'2/*' is not a valid [Day] crontab field expression.`

Best is you post a working code example of your problem.

**Comment by unosbaghaie** [comment]
thanks for your reply 

check this 

` var occurances  =  NCrontab.CrontabSchedule
    .Parse("0 0 */2 * *")
    .GetNextOccurrences(new DateTime(2017, 1, 29), new DateTime(2017, 2, 5));`

**Comment by atifaziz** [comment]
`*/2` for the month field means _every 2nd day of the month_. That's separate for _each month_. It doesn't mean every second day of the year.

Have a look over at what [crontab.guru gives for your expression](https://crontab.guru/#0_0_*/2_*_*):

![image](https://cloud.githubusercontent.com/assets/20511/22324383/41742cd0-e3a9-11e6-83dd-f0130c5e5e5d.png)

It describes `0 0 */2 * *` as “At 00:00 on every 2nd day-of-month.” Moreover, it too yields occurrences consistent with NCrontab; that is it yields Jan 31st and then Feb 1st:

```
next at 2017-01-27 00:00:00
then at 2017-01-29 00:00:00
then at 2017-01-31 00:00:00
then at 2017-02-01 00:00:00
then at 2017-02-03 00:00:00
```

**Comment by atifaziz** [comment]
I'm closing this as by-design as the result is consistent with what the crontab expression says and other implementations.

**Comment by unosbaghaie** [comment]
hey dude, I think you didn't get what I mean, I want to say every two days . for example 
1/29/2017 
1/31/2017 
2/02/2017 
2/04/2017 
2/06/2017 
...
I think the pattern is correct but as you indicated in the picture, the title says "every 2nd day of the month" but the generated days are every two days . 

pay attention please 
`next at 2017-01-27 00:00:00
then at 2017-01-29 00:00:00
then at 2017-01-31 00:00:00
then at 2017-02-01 00:00:00
then at 2017-02-03 00:00:00`


thanks

**Comment by atifaziz** [comment]
Let's just look at two dates. Based on _your interpretation of the pattern_, you expect an occurrence of the schedule on **Jan 31st** then **Feb 2nd**. Correct? Instead, NCrontab is giving you **Jan 31st** then **Feb 1st**. In [your original post](https://github.com/atifaziz/NCrontab/issues/23#issue-203302549), you said that's the issue:

> that the issue is with 31st and 1st .

If you look at [the picture](https://cloud.githubusercontent.com/assets/20511/22324383/41742cd0-e3a9-11e6-83dd-f0130c5e5e5d.png), it also gives the same two days, that is, **Jan 31st** then **Feb 1st**:

    then at 2017-01-31 00:00:00
    then at 2017-02-01 00:00:00

_I think_ I've understood what you want but what I'm saying is that a [_crontab expression_](https://en.wikipedia.org/wiki/Cron#CRON_expression) doesn't capture that directly. Have a read to [the answer](http://unix.stackexchange.com/a/16094) to the question “[How can I tell cron to run a command every other day (odd/even)?](http://unix.stackexchange.com/questions/16093/how-can-i-tell-cron-to-run-a-command-every-other-day-odd-even)”.
