### ISSUE TITLE
ranges that cross over midnight

### ISSUE THREAD

**Issue by zumoshi** [atifaziz/NCrontab#24]
Hello,
I would like to report an unexpected behavior.

Cron:
`* 20-4 * * *`

I expect it to work as if written:
`* 20,21,22,...,3,4 * * *`

it works as if written:
`* 4,5,6,...,19,20 * * *`

I believe `20-4` should expand to `20-23,0-4` rather than `4-20`. since it makes little sense to write the numbers backwards. the original crontab considers midnight crossing ranges as invalid so either case is violating the original implantation, might as well implant the one that makes more sense.

I know that this was mentioned before in #14, but there was no alternatives proposed there.

**Comment by atifaziz** [comment]
As pointed out in #14, this won't work. In fact, I should disallow inverted ranges and throw an error instead to avoid confusion. You can also see on [crontab.guru](https://crontab.guru) that [`* 20-4 * * *` is considered invalid](https://crontab.guru/#*_20-4_*_*_*) (_hour_ is in red):

![image](https://cloud.githubusercontent.com/assets/20511/22380295/4502132a-e4bd-11e6-8d52-5d117eedda90.png)

Your best bet to get the result you want is to create two schedules, one that goes from hour 20 to 23 and another from 0 to 4. You can then use [`SortedMerge`](http://morelinq.github.io/2.0/ref/api/html/M_MoreLinq_MoreEnumerable_SortedMerge__1_1.htm) from [MoreLINQ](http://morelinq.github.io/) and `DistinctUntilChanged` from [System.Interactive](https://www.nuget.org/packages/System.Interactive) to merge both schedules into one, like this:

```c#
var bt = new DateTime(2000, 12, 4);
var et = bt.AddDays(2);
var s1 = NCrontab.CrontabSchedule.Parse("0 20-23 * * *");
var o1 = s1.GetNextOccurrences(bt, et);
var s2 = NCrontab.CrontabSchedule.Parse("0 0-4 * * *");
var o2 = s2.GetNextOccurrences(bt, et);

var ms =
    o1.SortedMerge(OrderByDirection.Ascending, o2)
      .DistinctUntilChanged();
      
foreach (var dt in ms)
    Console.WriteLine(dt);
```


```
04/12/2000 01:00:00
04/12/2000 02:00:00
04/12/2000 03:00:00
04/12/2000 04:00:00
04/12/2000 20:00:00
04/12/2000 21:00:00
04/12/2000 22:00:00
04/12/2000 23:00:00
05/12/2000 00:00:00
05/12/2000 01:00:00
05/12/2000 02:00:00
05/12/2000 03:00:00
05/12/2000 04:00:00
05/12/2000 20:00:00
05/12/2000 21:00:00
05/12/2000 22:00:00
05/12/2000 23:00:00
```

**Comment by atifaziz** [comment]
I'm going to close this because the behaviour is by-design. The right fix is to disallow such an expression to avoid confusion and which is now being tracked as issue #25.
