### ISSUE TITLE
Every n weeks

### ISSUE THREAD

**Issue by galiolas** [atifaziz/NCrontab#26]
Hello,

how could i get a recurrence every n weeks?
I read on forums that Cron cannot handle the every n weeks pattern, so in SQL with your DLL how could i do it? thanks

**Comment by atifaziz** [comment]
[Crontab expressions](https://github.com/atifaziz/NCrontab/wiki/Crontab-Expression) don't have a way to express what you're asking. With NCrontab, however, you could however build on top of a base schedule using LINQ. For example:

```c#
var schedule =
    CrontabSchedule
        .Parse("0 12 * * Mon")
        .GetNextOccurrences(baseTime: new DateTime(2000, 1, 1), endTime: new DateTime(2001, 1, 1))
        .TakeEvery(3);
foreach (var time in schedule)
    Console.WriteLine(time.ToString("ddd, dd MM yyyy HH:mm"));
```

The base schedule of the `0 12 * * Mon` expression yields Mondays midday. Then using [`TakeEvery`](http://morelinq.github.io/1.x/ref/api/html/T_MoreLinq_MoreEnumerable.htm) from [MoreLINQ](http://morelinq.github.io/), you can get the effect of _every third Monday, midday_.

**Comment by unionthugface** [comment]
I likewise am seeing a problem with CrontabSchedule.Parse with the following string:
```0 0 * 11 4-6/4```
This is parsed as `0 0 * 11 4`, and so GetNextOccurrences brings up all Thursdays -- not just the 4th one -- and ignores the Fridays and Saturdays requested.  Is my pattern wrong?

**Comment by atifaziz** [comment]
Closing this in the hope that the question is answered.
