### ISSUE TITLE
Slashes in days of week are experiencing trouble

### ISSUE THREAD

**Issue by unionthugface** [atifaziz/NCrontab#27]
I am seeing a problem with `CrontabSchedule.Parse` when there is a slash in the days-of-week field.  For instance the following string:
`0 0 * 11 4-6/4`
This is parsed as `0 0 * 11 4`, and so `GetNextOccurrences` brings up all Thursdays -- not just the 4th one -- and ignores the Fridays and Saturdays requested. Is my pattern wrong?

Another example, `0 0 * 1-2 Mon/3` becomes `0 0 * 1-2 1,4` (i.e. it turns "every 3rd Monday" into "every Monday and Thursday").

**Comment by atifaziz** [comment]
You're misunderstanding how slashes work in crontab expressions. The `/4` in `4-6/4` means _every 4th day-of-week_ and the `4-6` part means Thursday-Saturday and so the only day that qualifies for the _every 4th day-of-week_ is Thursday. If you hop over to [crontab.guru](https://crontab.guru) and [test the `0 0 * 11 4-6/4` expression](https://crontab.guru/#0_0_*_11_4-6/4), then you'll see the description it provides is “At 00:00 on every 4th day-of-week from Thursday through Saturday in November”:

![image](https://cloud.githubusercontent.com/assets/20511/23694792/0eb9f3ee-03dc-11e7-841b-7a93ac291878.png)

Then if you test the following against NCrontab in a C# Interactive session:

```
Microsoft (R) Visual C# Interactive Compiler version 1.3.1.60616
Copyright (C) Microsoft Corporation. All rights reserved.

Type "#help" for more information.
> #r "NCrontab.dll"
> using NCrontab;
> var dates =
.     from d in CrontabSchedule.Parse("0 0 * 11 4-6/4")
.                              .GetNextOccurrences(DateTime.Today, DateTime.MaxValue)
.                              .Take(5)
.     select d.ToString("dddd dd, MMM yyyy HH:mm");
> Console.WriteLine(string.Join(Environment.NewLine, dates));
Thursday 02, Nov 2017 00:00
Thursday 09, Nov 2017 00:00
Thursday 16, Nov 2017 00:00
Thursday 23, Nov 2017 00:00
Thursday 30, Nov 2017 00:00
```

you'll see that the occurrences match those in the screenshot from [crontab.guru](https://crontab.guru).

The problem with `0 0 * 1-2 Mon/3` is similar; a misinterpretation of the expression. [`Mon/3` means every 3rd day-of-week from Monday through Sunday](https://crontab.guru/#0_0_*_1-2_Mon/3), not every 3rd Monday.

Hope this clarifies things.

Closing as by-design.
