### ISSUE TITLE
Is seventh field invalid?

### ISSUE THREAD

**Issue by YoungjaeKim** [atifaziz/NCrontab#28]
`0 0 12 1/1 * ? *` is Invalid in NCronTab (created from [CronMaker](http://www.cronmaker.com/)) with below exception message, 

	CrontabSchedule.ParseOptions options = new CrontabSchedule.ParseOptions()
	{
		IncludingSeconds = true,
	};
	CrontabSchedule.Parse("0 0 12 1/1 * ? *", options);

> CrontabException: '0 0 12 1/1 * ? *' is an invalid crontab expression. It must contain 6 components of a schedule in the sequence of seconds, minutes, hours, days, months, and days of week.

But, _7th field is optional_ Year expression as official documentation described; http://www.quartz-scheduler.org/documentation/quartz-2.x/tutorials/tutorial-lesson-06

Did you consider it as an error?

**Comment by atifaziz** [comment]
NCrontab does not support a year field.

> But, _7th field is optional_ Year expression as official documentation described; http://www.quartz-scheduler.org/documentation/quartz-2.x/tutorials/tutorial-lesson-06

Who says that Quartz is _the official_ documentation on crontab expressions?

[According to Wikipedia](https://en.wikipedia.org/wiki/Cron#CRON_expression):

> [Year] field is not supported in standard/default implementations.

**Comment by YoungjaeKim** [comment]
Ah, got it.
thanks for clarify.
