### ISSUE TITLE
Why no year field?

### ISSUE THREAD

**Issue by Rui90** [atifaziz/NCrontab#30]
Why don't you provide the year definition? It does not make sense. Should I be able to say: run this task only once in this date? 20/2/2037?

**Comment by atifaziz** [comment]
This is by-design. See #28 for why.

> Should I be able to say: run this task only once in this date? 20/2/2037?

You don't need crontab to express that since it occurs once never repeats. A simple date should be fine for that.

**Comment by atifaziz** [comment]
Closing on the assumption the question is [answered](https://github.com/atifaziz/NCrontab/issues/30#issuecomment-303788743).

**Comment by thojaw** [comment]
It's not true that it doesn't make sense. I'd love to define the Expression `0 0 0 1 1 ? */2` which will run the Task every two years, on 01.01.2020, 01.01.2022, 01.01.2024 etc.

**Comment by atifaziz** [comment]
> It's not true that it doesn't make sense. I'd love to define the Expression `0 0 0 1 1 ? */2` which will run the Task every two years, on 01.01.2020, 01.01.2022, 01.01.2024 etc.

I agree but the opening comment in the issue was about a specific year and perhaps I was taking too literally. That said, I'm still not very inclined to add this since, as I said [my comment in #28](https://github.com/atifaziz/NCrontab/issues/28#issuecomment-292505232), it's non-standard:

> [According to Wikipedia](https://en.wikipedia.org/wiki/Cron#CRON_expression):
> 
> > [Year] field is not supported in standard/default implementations.

**Comment by thojaw** [comment]
> I agree but the opening comment in the issue was about a specific year and perhaps I was taking too literally. That said, I'm still not very inclined to add this since, as I said [my comment in #28](https://github.com/atifaziz/NCrontab/issues/28#issuecomment-292505232), it's non-standard:
> 
> > [According to Wikipedia](https://en.wikipedia.org/wiki/Cron#CRON_expression):
> > > [Year] field is not supported in standard/default implementations.

Understand, it's a pity that it (the standard implementation) limits the intervals to a period < 1 year. This appears quite shortsighted especially when using these expressions as a more general, useful notation to express intervals, e.g. when I have to renew my Car registration in May every 2 years.
