### ISSUE TITLE
Day ranges through Sunday

### ISSUE THREAD

**Issue by skewwhiffy** [atifaziz/NCrontab#31]
Failing test here: https://github.com/skewwhiffy/NCrontab/blob/DayRangeIssue/NCrontab.Tests/CrontabScheduleTests.cs#L381

A day range like SAT-MON is treated as an inverted range 6-1, rather than SAT,SUN,MON.

#25 is probably linked: certainly disallowing such ranges would be better behaviour than treating it as an inverted range.

Happy to try and fix this, just let me know.

**Comment by atifaziz** [comment]
> #25 is probably linked: certainly disallowing such ranges would be better behaviour than treating it as an inverted range.

Yes, #25 is the real issue/resolution so I'll close this and we can continue any discussion over at #25.
