### ISSUE TITLE
Support multiple schedules

### ISSUE THREAD

**Issue by atifaziz** [atifaziz/NCrontab#36]
Some complex schedules cannot be expressed in a single crontab expression, e.g. a schedule that occurs every 6 hours on weekdays but every 12 hours on weekends. This can be solved by supporting multiple schedules that are merged into one. In other words, given a sequence of `CrontabSchedule` instances, a method could be designed to produce _distinct and ordered_ occurrences.

**Comment by stevehansen** [comment]
sorry to comment on an old issue but is there any idea when a new version might be build with this fix?

**Comment by atifaziz** [comment]
@stevehansen The new [version 3.4](https://github.com/atifaziz/NCrontab/releases/tag/v3.4.0) that includes this feature is now available.
