### ISSUE TITLE
Make obvious in code/documentation that cron timing is better with UTC

### ISSUE THREAD

**Issue by Miggleness** [atifaziz/NCrontab#41]
I think there is value in being upfront that scheduling with cron is based on UTC, and not local time.

1. Update documentation
2. Update 'cron' arguments with 'cronUtc'

I can take this up granted the @atifaziz  does have free time to take up PRs 😀

**Comment by atifaziz** [comment]
I agree with #&#xfeff;1 but I'm less sure about the value of #&#xfeff;2. The documentation should just highlight the issue, that assuming local time can cause surprises like a schedule being potentially skipped when the clock moves back.

I welcome a PR for this (thanks for the offer) and I'll find the time to review as long as you don't hold me to a deadline! 😉 

Where do you plan to address this? The README file or XML documentation in the code?

**Comment by Miggleness** [comment]
Awesome, you're still active :)

And should be both README and XML documentation.

**Comment by Miggleness** [comment]
my apologies mate.  I realized I logged the issue on the wrong project, to which NCrontab is a dependency.  

Did look at the source and NCrontab appears to respect, or rather does not enforce anything that may not have been intentioned by the calling component.

**Comment by atifaziz** [comment]
> my apologies mate. I realized I logged the issue on the wrong project

LOL 😆and no worries. Just curious, what's the other project?

**Comment by Miggleness** [comment]
It’s cronDaemon.
