### ISSUE TITLE
Ability to provide Nth occurrence in cron expression

### ISSUE THREAD

**Issue by nilabhsagar** [atifaziz/NCrontab#59]
We have a requirement in which we wanted to run a job on every 2nd Sunday of a month. However we could not able to setup such cron expression like below

0 0 5 ? * 7#2
0 0 5 ? * SAT#2
The above expression mens At 05:00:00am, on the 2nd Saturday of the month, every month
Note #2 means every 2nd occurrence.

**Comment by atifaziz** [comment]
In this library, I want to stay true to the original crontab expression. If you have additional requirements for your application that means extending the expression, you could build it on top of NCrontab and in a more powerful and extensible manner. For example:

    cron_expression | filter

Then if you have this:

```
0 0 5 * * Sat | is_dow_ordinal(2)
```

You take the expression on the left of `|` and feed it to `CrontabSchedule.Parse`, get all occurrences of the schedule and then pass each occurrence through the `filter` predicate and use only those where the predicate evaluated to `true`.

**Comment by nilabhsagar** [comment]
Thank you
