### ISSUE TITLE
The type 'CrontabSchedule' exists in both 'NCrontab.Signed' and  'NCrontab'

### ISSUE THREAD

**Issue by jimmywim** [atifaziz/NCrontab#61]
Have installed via `dotnet add package ncrontab --version 3.3.1`

Added using statement: 
```
using NCrontab;
```

When trying to use `CrontabSchedule` like this:
```
 var cronSchedule = CrontabSchedule.Parse("15 35 * * *");
 cronSchedule.GetNextOccurrence(DateTime.Now);
```

 I get the following error:

```
The type 'CrontabSchedule' exists in both 'NCrontab.Signed, Version=3.2.20120.0, Culture=neutral, PublicKeyToken=5247b4370afff365' and 'NCrontab, Version=3.3.1.0, Culture=neutral, PublicKeyToken=null'
```

**Comment by atifaziz** [comment]
Somewhere in the dependency graph of your application, someone is referencing [ncrontab.signed at version 3.2.0](https://www.nuget.org/packages/ncrontab.signed/3.2.0). As the error says, the type `CrontabSchedule` is being found in both assemblies (NCrontab and NCrontab.Signed). You need to use one of the two packages/assemblies.
