### ISSUE TITLE
it can't parse cron string with '?'

### ISSUE THREAD

**Issue by colin-chang** [atifaziz/NCrontab#66]
when I try to parse a cron expression with '?' like `0 0 16 ? * SUN-THU`, I got an error message bellow:

`NCrontab.CrontabException: '?' is not a valid [Day] crontab field value. It must be a numeric value between 1 and 31 (all inclusive)`

**Comment by atifaziz** [comment]
NCrontab does not support [non-standard characters] and extensions like `?`. The [Crontab Expression] page describes the supported syntax.

I am closing this as by-design.

[non-standard characters]: https://en.wikipedia.org/wiki/Cron#Non-standard_characters
[Crontab Expression]: https://github.com/atifaziz/NCrontab/wiki/Crontab-Expression
