### ISSUE TITLE
Consider making public crontab field types private

### ISSUE THREAD

**Issue by atifaziz** [atifaziz/NCrontab#72]
Types like `ICrontabField` and `CrontabField` needn't be public. Not even the tests require their public access. Consider making them private for the next major release.

This is a design bug.

**Comment by MatisseHack** [comment]
This would be a breaking change for me. I certainly understand wanting to simplify the public interface, but I hope that `CrontabField` can be kept around 🤞

**Comment by atifaziz** [comment]
Abandoning based on [feedback](https://github.com/atifaziz/NCrontab/issues/71#issuecomment-717598099)  from @MatisseHack.
