### ISSUE TITLE
Support for L (Last day of month) or 5L (Last Friday of every month)

### ISSUE THREAD

**Issue by hgjura** [atifaziz/NCrontab#9]
Hello,

I have seen some cron implementations of L for (last day of month) or something like 5L (for last Friday of every month). Does NCrontab supports anything similar? Is there a way to impement these 2 scenarios with NCrontab. And if 'no' to both answers, is something in these lines envisioned to be added to future implementations?

Thanks
Herald

**Comment by atifaziz** [comment]
@hgjura No and no.

> And if 'no' to both answers, is something in these lines envisioned to be added to future implementations?

No plans but happy to consider a solid contribution with tests via a PR.
