### ISSUE TITLE
Remove necessity of ParseOptions

### ISSUE THREAD

**Issue by angelaki** [atifaziz/NCrontab#94]
Right now the only setting available is `IncludingSeconds`. But why does this need to be set at all? Right now I just use `IncludingSeconds = value.Split(' ').Length > 5`.

If actually wanted I'd recommend an enum e.g.

```
[Flags]
enum ParseMode : short
{
   Explicit,
   IncludeSeconds
};
```

with a default value of `IncludeSeconds`. This way you could still use `Explicit` or `Explicit | IncludeSeconds` for the current behavior and its generic by default.

**Comment by atifaziz** [comment]
> But why does this need to be set at all?

Because it's a more future-proof approach in case other options need to be added that may not be simple Booleans (which is what an `enum`-based approach with flags would be too).
