### ISSUE TITLE
Cron job defined for a specific date of the month but still running daily.

### ISSUE THREAD

**Issue by sarawalabs** [atifaziz/NCrontab#99]
Hi I have defined the below cron expression for a job, however this is still running daily, any idea how to make sure it should run on severy 6th of a month, be whichever day it is on that particula date.

"0 12 6 * *"

**Comment by atifaziz** [comment]
NCrontab does not do any scheduling of jobs. It simply parses a crontab expression and provides methods for generating `DateTime` instances that fit the schedule represented by the expression. Please provide code that demonstrates the problem where NCrontab produces `DateTime` instances other than at midday on the 6th of every month. Meanwhile, see [the timestamps produced by NCrontab for `0 12 6 * *`](https://ncrontab.swimburger.net/?expression=0+12+6+*+*).

**Comment by atifaziz** [comment]
I am going to close this, but happy to re-open once there is follow-up.
